# Generated by Django 5.1.1 on 2025-05-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
