# Generated by Django 5.1.1 on 2024-10-05 01:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/img/')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Carrusels',
                'db_table': 'carrusels',
            },
        ),
    ]
