# Generated by Django 5.1.1 on 2024-10-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrusel',
            old_name='name',
            new_name='title',
        ),
    ]
