# Generated by Django 5.1.1 on 2024-10-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_carrusel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrusel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
