# Generated by Django 5.1.1 on 2024-10-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carrusel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carrusel/img/'),
        ),
    ]
